components:
  schemas:
    Products:
      type: object
      required:
      - id
      - name
      - quantity
      - image
      - families_id
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        image:
          type: string
        families_id:
          type: integer
        weight:
          type: float

      example:
        id: 1
        name: "Name of product"
        quantity: 6
        image: "coca.png"
        families_id: 1

tags:
  name: Products
  description: Products operations
